language: go
sudo: false
go: 1.7.4
install:
# Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
go_import_path: github.com/VEVO/kubernetes-pod-discovery
