language: go
sudo: false
go: 1.7.4
install: godep restore -v ./...
script:
  - go test -v ./...
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
go_import_path: github.com/VEVO/kubernetes-pod-discovery
