language: go
sudo: false
go: 1.7.4
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tools/godep
install:
  - godep restore -v ./...
script:
  - go test -v ./...
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
go_import_path: github.com/VEVO/kubernetes-pod-discovery
