---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: nginx
  - port: 8080
    protocol: TCP
    name: endpoints
  selector:
    app: nginx
